before_install:
 - chmod +x mvnw
language: java
jdk:
  - oraclejdk8
before_script:
- mysql -u root -e 'CREATE DATABASE ponto_inteligente;'
- mysql -u root -e "CREATE USER 'root'@'localhost' IDENTIFIED BY '..ADMrc55264..';"
- mysql -u root -e "GRANT ALL ON ponto_inteligente.* TO 'root'@'localhost';"